#!/bin/bash
apt update -y
apt install -y ca-certificates

apt update -y

# 调整时区
export DEBIAN_FRONTEND="noninteractive"
apt install -y tzdata
cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# 更新和安装组件
apt full-upgrade -y
## 基础组件
apt install -y openssl curl vim wget zip unzip git lsof net-tools psmisc zlib1g gzip expect \
    dnsutils lrzsz screen apt-transport-https ca-certificates lsb-release apt-utils \
    aptitude software-properties-common sudo lvm2 gnupg tree nmon bash-completion htop \
    iputils-ping
## 扩展功能
apt install -y neofetch



# 优化终端操作及显示
sudo tee -a /root/.bashrc << EOF
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias grep='grep --color=auto'
alias ll='ls -l --color=auto'
alias ls='ls --color=auto'
PS1='[\${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\] \[\033[01;34m\]\W\[\033[00m\]]\\$ '
EOF

# 中文支持
apt install -y language-pack-zh-han*
dpkg-reconfigure locales
cat <<EOF > /etc/default/locale
LANG=zh_CN.UTF-8
LC_ALL=zh_CN.UTF-8
EOF

# 清理
apt clean

# 替换 systemctl
mv /usr/bin/systemctl /usr/bin/systemctl.bk
curl https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py > /usr/bin/systemctl
if [ "$?" != 0 ];then
    exit 1
fi
chmod +x /usr/bin/systemctl
