#!/bin/bash

# 更换 apt 源
mv /etc/apt/sources.list /etc/apt/sources.list.bk
cat <<EOF > /etc/apt/sources.list
deb http://mirrors.bfsu.edu.cn/ubuntu/ focal main restricted universe multiverse
# deb-src http://mirrors.bfsu.edu.cn/ubuntu/ focal main restricted universe multiverse
deb http://mirrors.bfsu.edu.cn/ubuntu/ focal-updates main restricted universe multiverse
# deb-src http://mirrors.bfsu.edu.cn/ubuntu/ focal-updates main restricted universe multiverse
deb http://mirrors.bfsu.edu.cn/ubuntu/ focal-backports main restricted universe multiverse
# deb-src http://mirrors.bfsu.edu.cn/ubuntu/ focal-backports main restricted universe multiverse
deb http://mirrors.bfsu.edu.cn/ubuntu/ focal-security main restricted universe multiverse
# deb-src http://mirrors.bfsu.edu.cn/ubuntu/ focal-security main restricted universe multiverse
# deb http://mirrors.bfsu.edu.cn/ubuntu/ focal-proposed main restricted universe multiverse
# deb-src http://mirrors.bfsu.edu.cn/ubuntu/ focal-proposed main restricted universe multiverse
EOF
apt update -y

# 调整时区
export DEBIAN_FRONTEND="noninteractive"
apt install -y tzdata
cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# 更新和安装组件
apt full-upgrade -y
## 基础组件
apt install -y openssl curl vim wget zip unzip git lsof net-tools psmisc zlib1g gzip expect \
    dnsutils lrzsz screen apt-transport-https ca-certificates lsb-release apt-utils \
    aptitude software-properties-common sudo lvm2 gnupg tree nmon bash-completion htop \
    iputils-ping
## 扩展功能
apt install -y neofetch
## Docker cli
mkdir -p /etc/apt/keyrings/
curl -fsSL https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://mirrors.bfsu.edu.cn/docker-ce/linux/ubuntu $(lsb_release -cs) stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
apt update -y
apt install -y docker-ce-cli
echo -e "export DOCKER_HOST=tcp://127.0.0.1:2375\n" >> /root/.bashrc

# 优化终端操作及显示
sudo tee -a /root/.bashrc << EOF
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias grep='grep --color=auto'
alias ll='ls -l --color=auto'
alias ls='ls --color=auto'
PS1='[\${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\] \[\033[01;34m\]\W\[\033[00m\]]\\$ '
EOF

# 中文支持
apt install -y language-pack-zh-han*
dpkg-reconfigure locales
cat <<EOF > /etc/default/locale
LANG=zh_CN.UTF-8
LC_ALL=zh_CN.UTF-8
EOF

# 清理
apt clean

# 替换 systemctl
mv /usr/bin/systemctl /usr/bin/systemctl.bk
curl https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py > /usr/bin/systemctl
if [ "$?" != 0 ];then
    exit 1
fi
chmod +x /usr/bin/systemctl